[workspace]
members = [
    "day1", "day2", "day3", "day4", "day5", "day6", "day7",
]
resolver="2"


[workspace.dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
nom = "7.1.3"
petgraph = "0.6.5"
thiserror = "2.0.3"

